name: build woof

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest # Only if we could have Debian... :(
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setting up Go env
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build woof
      run: |
        mkdir -p build
        EXT=""
        if [ "${{ matrix.os }}" = "windows" ]; then
          EXT=".exe"
        fi
        OUTPUT="woof-${{ matrix.os }}-${{ matrix.arch }}${EXT}"
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o build/$OUTPUT .

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: woof-${{ matrix.os }}-${{ matrix.arch }}
        path: build/woof-${{ matrix.os }}-${{ matrix.arch }}*
